name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip build setuptools
        pip install . .[test]
    - name: Lint/test with pre-commit
      run: SKIP=no-commit-to-branch pre-commit run --all-files

  # Make sure commit messages follow the conventional commits convention:
  # https://www.conventionalcommits.org
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - commitlint
    concurrency: release
    permissions:
      id-token: write
      contents: write
    environment:
      name: pypi
      url: https://pypi.org/p/aiojellyfin

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # This action uses Python Semantic Release v8
    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@v8.7.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
